apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: default
  namespace: servicemesh-con
spec:
  host: "*.servicemesh-con.svc.cluster.local"
  trafficPolicy:
   tls:
    mode: ISTIO_MUTUAL