apiVersion: v1
kind: ConfigMap
metadata:
  name: config-kafka-channel
  namespace: knative-eventing
data: 
  bootstrapServers: small-event-cluster.amq-streams:9092
  channelTemplateSpec: | 
    apiVersion: messaging.knative.dev/v1beta1
    kind: KafkaChannel
    spec:
      numPartitions: 3
      replicationFactor: 1