apiVersion: v1
kind: ConfigMap
metadata:
  name: config-br-defaults
  namespace: knative-eventing
data:
  default-br-config: |
    clusterDefault:
      apiVersion: v1
      brokerClass: MTChannelBasedBroker
      kind: ConfigMap
      name: config-imc-channel
      namespace: knative-eventing
    namespaceDefaults:
      newco-tenant: 
        apiVersion: v1
        brokerClass: InMemory
        kind: ConfigMap
        name: config-imc-channel
        namespace: newco-tenant
      servicemesh-con:
        apiVersion: v1
        brokerClass: KafkaBroker
        kind: ConfigMap
        name: config-smcon-tenant-channel
        namespace: servicemesh-con
      important-tenant: 
        brokerClass: KafkaBroker
        kind: ConfigMap
        name: important-tenant-channel
        namespace: important-tenant