apiVersion: operator.knative.dev/v1alpha1
kind: KnativeEventing
metadata:
  name: knative-eventing
  namespace: knative-eventing
spec: 
  defaultBrokerClass: MTChannelBasedBroker
  deployments: 
    - name: eventing-controller
      annotations:
       "sidecar.istio.io/inject": "true"
       "sidecar.istio.io/rewriteAppHTTPProbers": "true"
    - name: eventing-webhook 
      annotations:
       "sidecar.istio.io/inject": "true"
       "sidecar.istio.io/rewriteAppHTTPProbers": "true"
    - name: imc-controller 
      annotations:
       "sidecar.istio.io/inject": "true"
       "sidecar.istio.io/rewriteAppHTTPProbers": "true"
    - name: imc-dispatcher 
      annotations:
       "sidecar.istio.io/inject": "true"
       "sidecar.istio.io/rewriteAppHTTPProbers": "true"
    ## FIXME this doesn't seem to work
    - name: kafka-ch-controller
      annotations: 
       "sidecar.istio.io/inject": "true"
       "sidecar.istio.io/rewriteAppHTTPProbers": "true"
    - name: kafka-webhook
      annotations:
       "sidecar.istio.io/inject": "true"
       "sidecar.istio.io/rewriteAppHTTPProbers": "true"

