###FIXME mcostell...this likely needs to include some more stuffs 
apiVersion: maistra.io/v1
kind: ServiceMeshMemberRoll
metadata:
  name: default
  namespace: istio-system
spec:
  members: 
    - knative-serving
    - knative-eventing 
    - servicemesh-con

